<?php
/**
 * This file is part of The Official Amazon Payments Magento Extension
 * (c) creativestyle GmbH <amazon@creativestyle.de>
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_CheckoutByAmazon
 * @copyright  Copyright (c) 2011 - 2013 creativestyle GmbH (http://www.creativestyle.de)
 * @author     Marek Zabrowarny / creativestyle GmbH <amazon@creativestyle.de>
 */
?>
<div id="ProgressAmazonWalletWidget"></div>
<script type="text/javascript">//<![CDATA[
    new CBA.Widgets.WalletWidget({
        merchantId: '<?php echo $this->getMerchantId(); ?>',
        displayMode: 'Read',
<?php if ($this->getPurchaseContractId()): ?>
        purchaseContractId: '<?php echo $this->getPurchaseContractId(); ?>',
<?php endif; ?>
        design: {size: {width: '<?php echo $this->getWidgetWidth(); ?>', height: '<?php echo $this->getWidgetHeight(); ?>'}}
    }).render('ProgressAmazonWalletWidget') ;
//]]></script>
