<?php
/**
 * This file is part of The Official Amazon Payments Magento Extension
 * (c) creativestyle GmbH <amazon@creativestyle.de>
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_CheckoutByAmazon
 * @copyright  Copyright (c) 2011 - 2013 creativestyle GmbH (http://www.creativestyle.de)
 * @author     Marek Zabrowarny / creativestyle GmbH <amazon@creativestyle.de>
 */
?>
<div class="grid">
    <div class="hor-scroll">
        <table cellspacing="0" class="data simple-debug-section" id="<?php echo $this->getSectionId(); ?>">
            <colgroup>
                <?php if ($this->getShowKeys()): ?>
                    <col width="250">
                <?php endif; ?>
                <col />
            </colgroup>
            <tbody>
                <?php foreach ($this->getDebugInfo() as $key => $value): ?>
                    <?php if (is_array($value)): ?>
                        <?php $i = 0; foreach ($value as $subvalue): ?>
                            <tr>
                                <?php if ($i == 0 && $this->getShowKeys()): ?>
                                    <td rowspan="<?php echo count($value); ?>" class="a-right"><strong><?php echo $key; ?></strong></td>
                                <?php endif; ?>
                                <td class="a-left data-cell"><?php echo $subvalue; ?></td>
                            </tr>
                        <?php $i++; endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <?php if ($this->getShowKeys()): ?>
                                <td class="a-right"><strong><?php echo $key; ?></strong></td>
                            <?php endif; ?>
                            <td class="a-left data-cell"><?php echo $value; ?></td>
                        </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">//<![CDATA[
    document.observe('dom:loaded', function() {
        decorateTable('<?php echo $this->getSectionId(); ?>');
        var tableCells = $$('#<?php echo $this->getSectionId(); ?> td.data-cell');
        if (tableCells.length) {
            tableCells.each(function(cell) {
                if (cell.innerHTML.toLowerCase() == 'no' || cell.innerHTML.toLowerCase() == 'inactive' || cell.innerHTML.toLowerCase() == 'invalid') {
                    cell.update('<span class="amazon-failed" title="' + cell.innerHTML + '">' + cell.innerHTML + '</span>');
                } else if (cell.innerHTML.toLowerCase() == 'yes' || cell.innerHTML.toLowerCase() == 'ok') {
                    cell.update('<span class="amazon-passed" title="' + cell.innerHTML + '">' + cell.innerHTML + '</span>');
                }
            });
        }
    });
//]]></script>
