<?php
/**
 * This file is part of The Official Amazon Payments Magento Extension
 * (c) creativestyle GmbH <amazon@creativestyle.de>
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_CheckoutByAmazon
 * @copyright  Copyright (c) 2011 - 2013 creativestyle GmbH (http://www.creativestyle.de)
 * @author     Marek Zabrowarny / creativestyle GmbH <amazon@creativestyle.de>
 */
?>
<div class="block block-progress opc-block-progress">
    <div class="block-title">
        <strong><span><?php echo $this->helper('checkout')->__('Your Checkout Progress') ?></span></strong>
    </div>
    <div class="block-content">
        <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
            <?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>
                <?php echo $this->getShippingHtml(); ?>
            <?php endif; ?>
        <?php endif; ?>
        <dl>
            <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
                <?php if (!$this->getCheckout()->getStepData('shipping', 'complete')): ?>
                    <dt>
                        <?php echo $this->helper('checkout')->__('Shipping Address') ?>
                    </dt>
                <?php endif; ?>
            <?php endif; ?>
            <?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
                <?php if ($this->getCheckout()->getStepData('shipping_method', 'complete')): ?>
                    <dt class="complete">
                        <?php echo $this->helper('checkout')->__('Shipping Method') ?>
                    </dt>
                    <dd class="complete">
                        <?php if ($this->getShippingMethod()): ?>
                            <?php echo $this->getShippingDescription() ?>
                            <?php $_excl = $this->getShippingPriceExclTax(); ?>
                            <?php $_incl = $this->getShippingPriceInclTax(); ?>
                            <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                                <?php echo $_incl; ?>
                            <?php else: ?>
                                <?php echo $_excl; ?>
                            <?php endif; ?>
                            <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                (<?php echo $this->helper('checkout')->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                            <?php endif; ?>
                        <?php else: ?>
                            <?php echo $this->helper('checkout')->__('Shipping method has not been selected yet') ?>
                        <?php endif; ?>
                    </dd>
                <?php else: ?>
                    <dt>
                        <?php echo $this->helper('checkout')->__('Shipping Method') ?>
                    </dt>
                <?php endif; ?>
            <?php endif; ?>
            <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
                <?php if (!$this->getCheckout()->getStepData('payment', 'complete')): ?>
                    <dt>
                        <?php echo $this->helper('checkout')->__('Payment Method') ?>
                    </dt>
                <?php endif; ?>
            <?php endif; ?>
        </dl>
        <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
            <?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>
                <?php echo $this->getPaymentHtml(); ?>
            <?php endif; ?>
        <?php endif; ?>        
    </div>
</div>
